package:
  name: ccpi-viewer
  version: "0.1"


build:
  preserve_egg_dir: True
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - vtk
    
  run:
    - python
    - numpy
    - mkl
    - libxml2
    - libtiff
    - libpng
    - libiconv
    - jpeg

	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'