package:
  name: ccpi-viewer
  version: "0.1"


build:
  preserve_egg_dir: True
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - vtk
    - setuptools
 
  run:
    - python
    - numpy
    - vtk


	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache v.2.0 license
  summary: 'CCPi Core Imaging Library (Viewer)'